//tealium universal tag - utag.305 ut4.0.202601291031, Copyright 2026 Tealium.com Inc. All Rights Reserved.
!function(w){if(!w.rdt){var p=w.rdt=function(){p.sendEvent?p.sendEvent.apply(p,arguments):p.callQueue.push(arguments);};p.callQueue=[];}}(window);try{(function(id,loader){var u={id:id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={view:1,link:1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.toBoolean=function(val){val=String(val)||"";return val===true||val.toLowerCase()==="true"||val.toLowerCase()==="on";};u.clearEmptyKeys=function(object){Object.keys(object).forEach(function(key){if(object[key]===''||object[key]===undefined){delete object[key];}});return object;};u.mapFunc=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.mapFunc(arr,obj[i],item);}else{obj[i]=item;}};var EVENTS_LIST=["PageVisit","ViewContent","Search","AddToCart","AddToWishlist","Purchase","Lead","SignUp"];u.EVENTS_LIST_BY_NAME={PageVisit:"PageVisit",ViewContent:"ViewContent",Search:"Search",AddToCart:"AddToCart",AddToWishlist:"AddToWishlist",Purchase:"Purchase",Lead:"Lead",SignUp:"SignUp"};u.loaderCallback=function(){utag.DB('send:305:CALLBACK');u.initialized=true;u.callback();utag.DB('send:305:CALLBACK:COMPLETE');};u.callback=function(){u.data.event.forEach(function(eventName){u.sendEvent(eventName);});};u.sendEvent=function(eventName){var eventData={};switch(eventName){case u.EVENTS_LIST_BY_NAME.AddToCart:{eventData={itemCount:u.data.itemCount,value:u.data.value,currency:u.data.currency,}
break;}
case u.EVENTS_LIST_BY_NAME.Purchase:{eventData={itemCount:u.data.itemCount,value:u.data.value,currency:u.data.currency,transactionId:u.data.transactionId,}
break;}
case u.EVENTS_LIST_BY_NAME.AddToWishlist:{eventData={itemCount:u.data.itemCount,value:u.data.value,currency:u.data.currency,}
break;}
case u.EVENTS_LIST_BY_NAME.Lead:{eventData={value:u.data.value,currency:u.data.currency,transactionId:u.data.transactionId,}
break;}
case u.EVENTS_LIST_BY_NAME.SignUp:{eventData={value:u.data.value,currency:u.data.currency,transactionId:u.data.transactionId,}
break;}}
utag.ut.merge(eventData,u.data[eventName],1)
eventData=u.clearEmptyKeys(eventData);if(EVENTS_LIST.indexOf(eventName)>-1){rdt('track',eventName,eventData);}else{var customData={customEventName:eventName};utag.ut.merge(eventData,customData,1)
rdt('track','Custom',eventData);}}
u.map={"event:pdp_initialLoad":"ViewContent","event:addToTrolley":"AddToCart","potentialRevenueAddition":"AddToCart.value","potentialUnitsAddition":"AddToCart.itemCount","_ccurrency":"currency","orderTotal":"value","_cquan":"itemCount"};u.extend=[function(a,b){try{if(b['event'].toString().toLowerCase().indexOf('Confirmation'.toLowerCase())>-1){var itemCount=b._cquan
var totalItems=0
for(var i=0;i<itemCount.length;i++){totalItems+=itemCount[i]}
b._cquan=totalItems}}catch(e){utag.DB(e)}},function(a,b){try{if(1){b['orderTotal']=b['orderProductsTotal']}}catch(e){utag.DB(e);}}];u.send=function(utag_event,data_layer){if(u.ev[utag_event]||u.ev.all!==undefined){utag.DB("send:305");utag.DB(data_layer);var a,b,c,d,e,f,h,_event;a=utag_event;b=data_layer;u.data={account_id:"t2_8nwdpxefl",send_page_visit:"true",base_url:"//www.redditstatic.com/ads/pixel.js",itemCount:'',value:'',currency:'',transactionId:'',event:[]};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};utag.DB("send:305:EXTENSIONS");utag.DB(data_layer);Object.keys(utag.loader.GV(u.map)).forEach(function(mapping_key){if(data_layer[mapping_key]!==undefined&&data_layer[mapping_key]!==''){var destinations=u.map[mapping_key].split(',');destinations.forEach(function(parameter){u.mapFunc(parameter.split('.'),u.data,data_layer[mapping_key]);});}else{var event_destinations=mapping_key.split(':');if(event_destinations.length===2&&String(data_layer[event_destinations[0]])===String(event_destinations[1])){if(u.map[mapping_key]){u.data.event=u.data.event.concat(u.map[mapping_key].split(','));}}}});utag.DB("send:305:MAPPINGS");utag.DB(u.data);u.data.order_id=u.data.order_id||data_layer._corder||"";u.data.currency=u.data.currency||data_layer._ccurrency||"";if(u.data.event.length===0&&data_layer._cevent!==undefined){u.data.event=(u.typeOf(data_layer._cevent)==="array")?data_layer._cevent.slice(0):[data_layer._cevent];}
if(!u.data.account_id){utag.DB(u.id+": Tag not fired: Required attribute not populated");return;}
if(!u.initialized){rdt("init",u.data.account_id);if(u.toBoolean(u.data.send_page_visit)){rdt("track","PageVisit");}}
if(u.data.order_id){rdt("track","Purchase",u.clearEmptyKeys({itemCount:u.data.itemCount,value:u.data.value,currency:u.data.currency,transactionId:u.data.transactionId,}));}
if(u.initialized){u.callback();}else{if(!u.scriptrequested){u.initialized=true;u.scriptrequested=true;u.loader({type:"script",src:u.data.base_url,cb:u.loaderCallback,loc:"script",id:"utag_305",attrs:{}});}}
utag.DB("send:305:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("305","argos.main"));}catch(error){utag.DB(error);}
