//tealium universal tag - utag.355 ut4.0.202601291031, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1,'link':1};u.initialized=false;u.map={};u.extend=[function(a,b,c,d,e,f,g){if(1){d=b['tealium_environment'];if(typeof d=='undefined')return;c=[{'prod':'G-JWCPD5SJK1'},{'qa':'G-CM9YRX82EG'},{'dev':'G-CM9YRX82EG'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d.toString().indexOf(f)>-1){b['ga_measurement_id']=c[e][f];m=true};};if(m)break};}},function(a,b){try{if(1){var productsList=[]
switch(b.tealium_event){case'ev | Add to Trolley':var product=b.evtData.attributes.product[0]
productsList.push({id:product.id,quantity:product.quantity})
break;case'pl | pdp':productsList.push({id:b.productID,quantity:1})
break;case'pl | PLPResult':break;case'pl | searchResults':break;case'pl | pdp_initialLoad':productsList.push({id:b.productID,quantity:1})
break;case'pl | PLPResults':break;case'CLPResults':break;case'pl | orderConfirmation':for(var i=0;i<b['_cprod'].length;i++){productsList.push({id:b['_cprod'][i],quantity:b['_cquan'][i],item_price:b.unitRevenue[i]})}
break;case'Page View':if(b.pageName=='ar:trolley:prepay:confirmation:'||b.pageName=='ar:trolley:buy:confirmationpage:'){for(var i=0;i<b['_cprod'].length;i++){productsList.push({id:b['_cprod'][i],quantity:b['_cquan'][i],item_price:b.unitRevenue[i]})}}
break;}
if(productsList.length>0){b.facebookContents=productsList}}}catch(e){utag.DB(e)}},function(a,b){try{if(b['tealium_event'].toString().toLowerCase()=='ev | Add to Trolley'.toLowerCase()){let productNameArr=[];let cost=b.potentialRevenueAddition;let totalPrice=cost.reduce(function(acc,item){return acc+item;},0);productNameArr.push(b.productName);b.ga_productName=productNameArr;b.orderTotal=totalPrice;b.productPrice=b.potentialRevenueAddition;}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
window.dataLayer=window.dataLayer||[];function gtag(){if(typeof dataLayer!="undefined"){dataLayer.push(arguments)}};gtag('js',new Date());gtag('consent','update',{'analytics_storage':b.ga_analytics,'ad_storage':b.ga_ads,'ad_user_data':b.ga_aduser_data,'ad_personalization':b.ga_ad_personalization});gtag('config',b.ga_measurement_id,{'server_container_url':'https://dmt.argos.co.uk','first_party_collection':true,'send_page_view':false});if(!window.utag.data.utag_threeFiftyFive_loaded){gtag('event','page_view',{'event_id':'page_view_'+b.tealium_timestamp_local+b.tealium_random,'user_id':b.customerId,'send_to':b.ga_measurement_id});window.utag.data.utag_threeFiftyFive_loaded=true;}
if(b.tealium_event=='ev | Add to Trolley'){var items=[];for(var i=0;i<b.potentialUnitsAddition.length;i++){items.push({'item_id':b.productId&&b.productId[i]?b.productId[i]:'','item_name':b.ga_productName[i],'price':b.potentialRevenueAddition[i]});}
gtag('event','add_to_cart',{'currency':b._ccurrency,'value':b.orderTotal,'items':items,'u1':b.productName,'u3':b.synapticaCategoryId,'u11':b.customerId||digitalData.user[0].profile[0].profileInfo.profileID,'u18':b.productId,'u40':b.potentialRevenueAddition,'fb_content_ids':JSON.stringify(b.productId),'fb_contents':JSON.stringify(b.facebookContents),'user_id':b.customerId,'event_id':'add_to_cart_'+b.tealium_timestamp_local+b.tealium_random,'send_to':b.ga_measurement_id});}
}};utag.o[loader].loader.LOAD(id);})("355","argos.main");}catch(error){utag.DB(error);}
