/*
 For license information please see main.js.LICENSE.txt */
(function(u){var t=window.AmazonUIPageJS||window.P,E=t._namespace||t.attributeErrors,q=E?E("PRIVCONAssets@centralized-prompting",""):t;q.guardFatal?q.guardFatal(u)(q,window):q.execute(function(){u(q,window)})})(function(u,t,E){function q(k,t,q){t in k?Object.defineProperty(k,t,{value:q,enumerable:!0,configurable:!0,writable:!0}):k[t]=q;return k}var g="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(k){return typeof k}:function(k){return k&&"function"===typeof Symbol&&k.constructor===
Symbol&&k!==Symbol.prototype?"symbol":typeof k};u.when("3p-promise").register("@amzn/consent-orchestration-client-sdk",function(k){var q;(function(){function u(a){var b;(b=function(a){if(Array.isArray(a))return L(a)}(a))||(b="undefined"!=typeof Symbol&&null!=a[Symbol.iterator]||null!=a["@@iterator"]?Array.from(a):void 0);if(!(a=b||function(a,b){if(a){if("string"==typeof a)return L(a,b);var c={}.toString.call(a).slice(8,-1);return"Object"===c&&a.constructor&&(c=a.constructor.name),"Map"===c||"Set"===
c?Array.from(a):"Arguments"===c||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(c)?L(a,b):void 0}}(a)))throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");return a}function L(a,b){(null==b||b>a.length)&&(b=a.length);for(var e=0,c=Array(b);e<b;e++)c[e]=a[e];return c}function r(){for(var a=arguments.length,b=Array(a),e=0;e<a;e++)b[e]=arguments[e];return b.filter(function(a){return a}).join(".")}
function x(){for(var a=[],b=arguments.length,e=Array(b),c=0;c<b;c++)e[c]=arguments[c];e.forEach(function(b){Array.isArray(b)?a.push.apply(a,u(b)):a.push(b)});b=a.filter(function(a){return"string"==typeof a&&""!==a.trim()}).map(function(a){return a.replace(/,/g,"-")});return r.apply(void 0,u(b))}function p(a){return p="function"==typeof Symbol&&"symbol"==g(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":g(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&
a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":g(a)},p(a)}function T(a,b){for(var e=0;e<b.length;e++){var c=b[e];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(a,M(c.key),c)}}function C(a,b,e){return(b=M(b))in a?Object.defineProperty(a,b,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[b]=e,a}function M(a){a:if("object"==p(a)&&a){var b=a[Symbol.toPrimitive];if(void 0!==b){a=b.call(a,"string");if("object"!=p(a))break a;throw new TypeError("@@toPrimitive must return a primitive value.");
}a=String(a)}return"symbol"==p(a)?a:a+""}function N(a,b){(null==b||b>a.length)&&(b=a.length);for(var e=0,c=Array(b);e<b;e++)c[e]=a[e];return c}function E(a){return a>Date.now()-O.promptTimeWindow*Z}function w(a){var b=Date.now();return a>=O.promptsUntilCooldown?b+O.readCooldownDuration*Z:void 0}function v(a){return v="function"==typeof Symbol&&"symbol"==g(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":g(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&
a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":g(a)},v(a)}function z(a,b){var e=Object.keys(a);if(Object.getOwnPropertySymbols){var c=Object.getOwnPropertySymbols(a);b&&(c=c.filter(function(b){return Object.getOwnPropertyDescriptor(a,b).enumerable}));e.push.apply(e,c)}return e}function F(a){for(var b=1;b<arguments.length;b++){var e=null!=arguments[b]?arguments[b]:{};b%2?z(Object(e),!0).forEach(function(b){var c,h=e[b];a:if("object"==v(b)&&b){var d=b[Symbol.toPrimitive];if(void 0!==
d){b=d.call(b,"string");if("object"!=v(b))break a;throw new TypeError("@@toPrimitive must return a primitive value.");}b=String(b)}(c="symbol"==v(b)?b:b+"")in a?Object.defineProperty(a,c,{value:h,enumerable:!0,configurable:!0,writable:!0}):a[c]=h}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(e)):z(Object(e)).forEach(function(b){Object.defineProperty(a,b,Object.getOwnPropertyDescriptor(e,b))})}return a}function P(a,b){var e,c=Q(a,b),d=(e=c.prompts,[Date.now()].concat(function(a){if(Array.isArray(a))return N(a)}(e)||
function(a){if("undefined"!=typeof Symbol&&null!=a[Symbol.iterator]||null!=a["@@iterator"])return Array.from(a)}(e)||function(a,b){if(a){if("string"==typeof a)return N(a,b);var c={}.toString.call(a).slice(8,-1);return"Object"===c&&a.constructor&&(c=a.constructor.name),"Map"===c||"Set"===c?Array.from(a):"Arguments"===c||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(c)?N(a,b):void 0}}(e)||function(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
}()).filter(E).sort(function(a,b){return b-a}).slice(0,O.promptsUntilCooldown));R(a,{principal:c.principal,prompts:d,defer:w(d.length)},b)}function Q(a,b){var e,c,d,h,k=a.id(),f={principal:k,prompts:[]};try{var U=a.get(fa);if(!U)return f;var n=JSON.parse(t.atob(U));return b.emitCount(r(b.appName,l.SERVICE,l.STORE,l.READ)),n.principal===k||(e=k,c=null!==(h=c=n.principal)&&void 0!==h?h:"",(e=null!==(d=e)&&void 0!==d?d:"").length!=c.length&&e.startsWith(c))?F(F({},n),{},{principal:k}):f}catch(ha){return b.emitCount(r(b.appName,
l.SERVICE,l.STORE,l.READ,l.ERROR)),f}}function R(a,b,e){try{var c=t.btoa(JSON.stringify(b));a.set(fa,c);e.emitCount(r(e.appName,l.SERVICE,l.STORE,l.WRITE))}catch(ea){e.emitCount(r(e.appName,l.SERVICE,l.STORE,l.WRITE,l.ERROR))}}function D(a){return D="function"==typeof Symbol&&"symbol"==g(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":g(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":
g(a)},D(a)}function y(a){var b="function"==typeof Map?new Map:void 0;return y=function(a){function c(){return function(a,b,c){if(d())return Reflect.construct.apply(null,arguments);var e=[null];e.push.apply(e,b);e=new (a.bind.apply(a,e));return c&&f(e,c.prototype),e}(a,arguments,n(this).constructor)}if(null===a||!function(a){try{return-1!==Function.toString.call(a).indexOf("[native code]")}catch(h){return"function"==typeof a}}(a))return a;if("function"!=typeof a)throw new TypeError("Super expression must either be null or a function");
if(void 0!==b){if(b.has(a))return b.get(a);b.set(a,c)}return c.prototype=Object.create(a.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}}),f(c,a)},y(a)}function d(){try{var a=!Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){}))}catch(b){}return(d=function(){return!!a})()}function f(a,b){return f=Object.setPrototypeOf?Object.setPrototypeOf.bind():function(a,b){return a.__proto__=b,a},f(a,b)}function n(a){return n=Object.setPrototypeOf?Object.getPrototypeOf.bind():
function(a){return a.__proto__||Object.getPrototypeOf(a)},n(a)}function V(a){return V="function"==typeof Symbol&&"symbol"==g(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":g(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":g(a)},V(a)}function aa(){function a(a,b,c){return Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}),a[b]}function b(a,b,J,e){b=Object.create((b&&
b.prototype instanceof c?b:c).prototype);e=new q(e||[]);return w(b,"_invoke",{value:U(a,J,e)}),b}function e(a,b,c){try{return{type:"normal",arg:a.call(b,c)}}catch(ka){return{type:"throw",arg:ka}}}function c(){}function d(){}function h(){}function f(b){["next","throw","return"].forEach(function(c){a(b,c,function(a){return this._invoke(c,a)})})}function n(a,b){function c(m,d,G,J){m=e(a[m],a,d);if("throw"!==m.type){var A=m.arg;return(m=A.value)&&"object"==V(m)&&u.call(m,"__await")?b.resolve(m.__await).then(function(a){c("next",
a,G,J)},function(a){c("throw",a,G,J)}):b.resolve(m).then(function(a){A.value=a;G(A)},function(a){return c("throw",a,G,J)})}J(m.arg)}var m;w(this,"_invoke",{value:function(a,e){function d(){return new b(function(b,m){c(a,e,b,m)})}return m=m?m.then(d,d):d()}})}function U(a,b,c){var m=C;return function(d,G){if(m===D)throw Error("Generator is already running");if(m===I){if("throw"===d)throw G;return{value:g,done:!0}}c.method=d;for(c.arg=G;;){if(d=c.delegate)if(d=l(d,c)){if(d===B)continue;return d}if("next"===
c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(m===C)throw m=I,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);m=D;d=e(a,b,c);if("normal"===d.type){if(m=c.done?I:F,d.arg===B)continue;return{value:d.arg,done:c.done}}"throw"===d.type&&(m=I,c.method="throw",c.arg=d.arg)}}}function l(a,b){var c=b.method,m=a.iterator[c];if(m===g)return b.delegate=null,"throw"===c&&a.iterator.return&&(b.method="return",b.arg=g,l(a,b),"throw"===b.method)||"return"!==c&&(b.method=
"throw",b.arg=new TypeError("The iterator does not provide a '"+c+"' method")),B;c=e(m,a.iterator,b.arg);return"throw"===c.type?(b.method="throw",b.arg=c.arg,b.delegate=null,B):(c=c.arg)?c.done?(b[a.resultName]=c.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=g),b.delegate=null,B):c:(b.method="throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,B)}function ha(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);
this.tryEntries.push(b)}function r(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function q(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(ha,this);this.reset(!0)}function t(a){if(a||""===a){var b=a[y];if(b)return b.call(a);if("function"==typeof a.next)return a;if(!isNaN(a.length)){var c=-1;b=function A(){for(;++c<a.length;)if(u.call(a,c))return A.value=a[c],A.done=!1,A;return A.value=g,A.done=!0,A};return b.next=b}}throw new TypeError(V(a)+" is not iterable");}aa=function(){return p};
var g,p={},x=Object.prototype,u=x.hasOwnProperty,w=Object.defineProperty||function(a,b,c){a[b]=c.value},v="function"==typeof Symbol?Symbol:{},y=v.iterator||"@@iterator",W=v.asyncIterator||"@@asyncIterator",z=v.toStringTag||"@@toStringTag";try{a({},"")}catch(m){a=function(a,b,c){return a[b]=c}}p.wrap=b;var C="suspendedStart",F="suspendedYield",D="executing",I="completed",B={};v={};a(v,y,function(){return this});var H=Object.getPrototypeOf;(H=H&&H(H(t([]))))&&H!==x&&u.call(H,y)&&(v=H);var K=h.prototype=
c.prototype=Object.create(v);return d.prototype=h,w(K,"constructor",{value:h,configurable:!0}),w(h,"constructor",{value:d,configurable:!0}),d.displayName=a(h,z,"GeneratorFunction"),p.isGeneratorFunction=function(a){a="function"==typeof a&&a.constructor;return!!a&&(a===d||"GeneratorFunction"===(a.displayName||a.name))},p.mark=function(b){return Object.setPrototypeOf?Object.setPrototypeOf(b,h):(b.__proto__=h,a(b,z,"GeneratorFunction")),b.prototype=Object.create(K),b},p.awrap=function(a){return{__await:a}},
f(n.prototype),a(n.prototype,W,function(){return this}),p.AsyncIterator=n,p.async=function(a,c,d,e,h){void 0===h&&(h=k);var m=new n(b(a,c,d,e),h);return p.isGeneratorFunction(c)?m:m.next().then(function(a){return a.done?a.value:m.next()})},f(K),a(K,z,"Generator"),a(K,y,function(){return this}),a(K,"toString",function(){return"[object Generator]"}),p.keys=function(a){var b=Object(a),c=[],d;for(d in b)c.push(d);return c.reverse(),function S(){for(;c.length;){var a=c.pop();if(a in b)return S.value=a,
S.done=!1,S}return S.done=!0,S}},p.values=t,q.prototype={constructor:q,reset:function(a){if(this.prev=0,this.next=0,this.sent=this._sent=g,this.done=!1,this.delegate=null,this.method="next",this.arg=g,this.tryEntries.forEach(r),!a)for(var b in this)"t"===b.charAt(0)&&u.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=g)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,d){return m.type="throw",
m.arg=a,c.next=b,d&&(c.method="next",c.arg=g),!!d}if(this.done)throw a;for(var c=this,d=this.tryEntries.length-1;0<=d;--d){var e=this.tryEntries[d],m=e.completion;if("root"===e.tryLoc)return b("end");if(e.tryLoc<=this.prev){var h=u.call(e,"catchLoc"),f=u.call(e,"finallyLoc");if(h&&f){if(this.prev<e.catchLoc)return b(e.catchLoc,!0);if(this.prev<e.finallyLoc)return b(e.finallyLoc)}else if(h){if(this.prev<e.catchLoc)return b(e.catchLoc,!0)}else{if(!f)throw Error("try statement without catch or finally");
if(this.prev<e.finallyLoc)return b(e.finallyLoc)}}}},abrupt:function(a,b){for(var c=this.tryEntries.length-1;0<=c;--c){var d=this.tryEntries[c];if(d.tryLoc<=this.prev&&u.call(d,"finallyLoc")&&this.prev<d.finallyLoc){var e=d;break}}e&&("break"===a||"continue"===a)&&e.tryLoc<=b&&b<=e.finallyLoc&&(e=null);c=e?e.completion:{};return c.type=a,c.arg=b,e?(this.method="next",this.next=e.finallyLoc,B):this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;return"break"===a.type||"continue"===
a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&b&&(this.next=b),B},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),r(c),B}},catch:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var d=a.arg;r(c)}return d}}throw Error("illegal catch attempt");
},delegateYield:function(a,b,c){return this.delegate={iterator:t(a),resultName:b,nextLoc:c},"next"===this.method&&(this.arg=g),B}},p}function W(a,b,d,c,f,h,n){try{var e=a[h](n),l=e.value}catch(ja){return void d(ja)}e.done?b(l):k.resolve(l).then(c,f)}function ba(){var a;return a=aa().mark(function ea(a,c){var d,e,f=arguments;return aa().wrap(function(h){for(;;)switch(h.prev=h.next){case 0:d=2<f.length&&void 0!==f[2]?f[2]:3,e=0;case 2:return h.prev=2,h.next=5,a(c);case 5:return h.abrupt("return",h.sent);
case 8:if(h.prev=8,h.t0=h.catch(2),!(++e>=d)){h.next=13;break}throw h.t0;case 13:return h.next=15,new k(function(a){return setTimeout(a,100)});case 15:if(e<d){h.next=2;break}case 16:case "end":return h.stop()}},ea,null,[[2,8]])}),ba=function(){var d=this,c=arguments;return new k(function(e,h){function f(a){W(n,e,h,f,k,"next",a)}function k(a){W(n,e,h,f,k,"throw",a)}var n=a.apply(d,c);f(void 0)})},ba.apply(this,arguments)}function I(a,b,d,c){var e=b.appName;return function(a,b){return ba.apply(this,
arguments)}(a,c,4<arguments.length&&void 0!==arguments[4]?arguments[4]:3).then(function(a){return b.emitCount(r(e,l.SERVICE,x(null==c?void 0:c.metricDimensions),d)),a}).catch(function(a){throw b.emitCount(r(e,l.SERVICE,d,l.ERROR)),new ca("failed to ".concat(d.toLowerCase()," consent for ").concat(e),a);})}function Y(a,b,d,c){var e=b||la,h=d||ma;return c&&ia.adaptiveBackoff.updateConfig(c),{prompt:function(){return function(a,b,c){var d=b.appName;return function(a,b){var c;a=Q(a,b);return Date.now()>
(null!==(c=a.defer)&&void 0!==c?c:0)}(c,b)?a().then(function(a){return b.emitCount(r(d,l.SERVICE,x(null==a?void 0:a.metricDimensions),l.PROMPT)),P(c,b),a}).catch(function(a){var e,h=a.status||(null===(e=a.http)||void 0===e?void 0:e.status)||0;if(429!==h&&204!==h)throw b.emitCount(r(d,l.SERVICE,l.PROMPT,l.ERROR)),new ca("failed to prompt for consent for "+d,a);a=Q(c,b);R(c,{principal:a.principal,prompts:a.prompts,defer:Date.now()+O.writeCooldownDuration*Z},b);!0}):function(a){return new k(function(b){a.emitCount(r(a.appName,
l.SERVICE,l.PROMPT,l.SKIP));b(null)})}(b)}(a.prompt,e,h)},accept:function(b){return I(a.accept,e,l.ACCEPT,b)},decline:function(b){return I(a.decline,e,l.DECLINE,b)},customize:function(b){return function(a,b,c){var d=b.appName;return a(c).then(function(a){return b.emitCount(r(d,l.SERVICE,x(null==c?void 0:c.metricDimensions),l.CUSTOMIZE)),a}).catch(function(a){throw b.emitCount(r(d,l.SERVICE,l.CUSTOMIZE,l.ERROR)),new ca("failed to customize consent for "+d,a);})}(a.customize,e,b)}}}var X={d:function(a,
b){for(var d in b)X.o(b,d)&&!X.o(a,d)&&Object.defineProperty(a,d,{enumerable:!0,get:b[d]})},o:function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},r:function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})}},da={};X.r(da);X.d(da,{initialize:function(){return Y}});var l=function(a){return a.SERVICE="cos",a.PROMPT="prompt",a.ACCEPT="accept",a.DECLINE="decline",a.CUSTOMIZE="customize",
a.STORE="store",a.READ="read",a.WRITE="write",a.ERROR="error",a.SKIP="skip",a}({}),la={appName:"unknown",emitCount:function(a,b){},emitTiming:function(a,b){}},ia={adaptiveBackoff:new (function(){return a=function c(){if(!(this instanceof c))throw new TypeError("Cannot call a class as a function");!0;C(this,"_promptsUntilCooldown",5);C(this,"_promptTimeWindow",10);C(this,"_readCooldownDuration",15);C(this,"_writeCooldownDuration",1440)},b=[{key:"promptsUntilCooldown",get:function(){return this._promptsUntilCooldown},
set:function(a){this._promptsUntilCooldown=a}},{key:"promptTimeWindow",get:function(){return this._promptTimeWindow},set:function(a){this._promptTimeWindow=a}},{key:"readCooldownDuration",get:function(){return this._readCooldownDuration},set:function(a){this._readCooldownDuration=a}},{key:"writeCooldownDuration",get:function(){return this._writeCooldownDuration},set:function(a){this._writeCooldownDuration=a}},{key:"updateConfig",value:function(a){this._promptsUntilCooldown=a.promptsUntilCooldown;
this._promptTimeWindow=a.promptTimeWindow;this._readCooldownDuration=a.readCooldownDuration;this._writeCooldownDuration=a.writeCooldownDuration}},{key:"getConfig",value:function(){return{promptsUntilCooldown:this._promptsUntilCooldown,promptTimeWindow:this._promptTimeWindow,readCooldownDuration:this._readCooldownDuration,writeCooldownDuration:this._writeCooldownDuration}}}],T(a.prototype,b),Object.defineProperty(a,"prototype",{writable:!1}),a;var a,b}())},O=ia.adaptiveBackoff,Z=6E4,fa="sp-cc-pcl",
ma={id:function(){return"unknown"},set:function(a,b){},get:function(a){return""}},ca=function(a){function b(a,e){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var c=b;var f=[a];c=n(c);c=d()?Reflect.construct(c,f||[],n(this).constructor):c.apply(this,f);if(!c||"object"!=D(c)&&"function"!=typeof c){if(void 0!==c)throw new TypeError("Derived constructors may only return object or undefined");if(void 0===this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
c=this}return c.message=a,c.cause=e,c.cause=e,c.name="ConsentOrchestrationError",Object.setPrototypeOf(c,b.prototype),c}return function(a,b){if("function"!=typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});Object.defineProperty(a,"prototype",{writable:!1});b&&f(a,b)}(b,a),e=b,Object.defineProperty(e,"prototype",{writable:!1}),e;var e}(y(Error));q=da})();return q});
"use strict";u.when("A","3p-promise","a-util","@amzn/consent-orchestration-client-sdk","ready").execute("centralized-prompting",function(k,g,E,L){var r,x,p=function(){},T={0:(r={name:"cc.banner"},q(r,"NO_VALUE","bannerPopUp"),q(r,"REJECT_ALL",".rejectall.linkbutton"),r),4:{name:"ads.banner"},5:{name:"datashare.banner"},42:{name:"quebec.banner"}},C=(x={},q(x,"NO_VALUE",".popup"),q(x,"ACCEPT_ALL",".acceptAll"),q(x,"REJECT_ALL",".rejectall"),q(x,"ACCEPT_PARTIAL",".customize"),x),M=function(d){return new g(function(f,
n){k.post("/privacyprefs/retail/v3/banner",{params:{consent:d.payload.url,consentTypes:d.consentTypes},paramsFormat:"json",accepts:"application/json",contentType:"application/json",timeout:5E3,headers:{"anti-csrftoken-a2z":d.csrfToken},success:function(d){f(d)},error:function(d){n(d)}})})},N=["x-acb","x-main","x-tacb"],Y=function(){return t.fwcimData&&fwcimData.customerId||Object.keys(E.cookies.getAll()||{}).some(function(d){return N.some(function(f){return d.startsWith(f)})})?"1":"0"},w=k.capabilities.localStorage?
localStorage:{getItem:function(d){return null},setItem:p,removeItem:p};r=t.ue&&"function"===typeof ue.count?function(d){return ue.count(d,1)}:p;var v=t.uet&&t.uex?{start:function(){return uet("bb","centralizedConsentBanner",{wb:1})},stop:function(){return uex("ld","centralizedConsentBanner",{wb:1})}}:{start:p,stop:p};v.start();var z=L.initialize({prompt:function(){return new g(function(d,f){k.get("/privacyprefs/retail/v3/banner",{success:function(n){n||f(Error("No Data"));var g=document.createElement("div");
g.id="sp-cc-wrapper";g.innerHTML=n;n=g.querySelector('input[type\x3d"hidden"][name\x3d"disclosureDecision"]');g={banner:g,metricDimensions:[n?n.value:"unknown"]};w.getItem("sp-cc-pending")&&(n=g.banner.querySelector("#sp-cc-error"))&&(n.className=(" "+n.className+" ").replace(" aok-hidden "," "));w.removeItem("sp-cc-pending");Q(g.banner);y(k.$("#cos-banner"),"NO_VALUE");d(g)},error:function(d){f(d)}})})},accept:function(d){return M(d)},decline:function(d){return M(d)},customize:function(d){return new g(function(f){f(d)})}},
{appName:"sp",emitCount:r,emitTiming:p},{id:function(){var d=E.cookies.get("session-id")+"|"+Y();return t.fwcimData&&fwcimData.customerId?d+"|"+fwcimData.customerId:d},get:function(d){return w.getItem(d)},set:function(d,f){return w.setItem(d,f)}},{promptsUntilCooldown:5,promptTimeWindow:10,readCooldownDuration:15,writeCooldownDuration:1440}),F=void 0,P=function(){var d=k.$("#cos-banner").outerHeight();"number"!==typeof d||0>=d?document.querySelector("html").style.removeProperty("scroll-padding-bottom"):
(d+="px",k.capabilities.mobile?document.querySelector("#a-page").style.marginBottom=d:document.body.style.paddingBottom=d,document.querySelector("html").style.setProperty("scroll-padding-bottom",d))},Q=function(d){var f=k.$("#a-page \x3e *:not(script)").first();f.length?f.before(d):document.body.appendChild(d);u.when("a-expander").execute(function(d){d.initializeExpanders()})};z.prompt().then(function(){v.stop();F=k.on("orientationchange resize",P);P()}).catch(function(d){v.stop();throw d;});var R=
function(){k.$("#sp-cc-wrapper").remove();w.setItem("sp-cc-pending","1");F&&k.off(F);P()},D=function(d,f){f.$event.preventDefault();var k=d.find('[name\x3d"anti-csrftoken-a2z"]'),g=d.find('[name\x3d"disclosureDecision"]');d=d.find('[name\x3d"consentTypes"]').val();return{payload:f.data,csrfToken:k.val(),metricDimensions:[g.val()],consentTypes:d}};k.declarative("banner-accept-all","click",function(d){var f=k.$("#cos-banner");d=D(f,d);R();z.accept(d).then(function(){w.removeItem("sp-cc-pending");y(f,
"ACCEPT_ALL")})});k.declarative("banner-reject-all","click",function(d){var f=k.$("#cos-banner");d=D(f,d);R();z.decline(d).then(function(){w.removeItem("sp-cc-pending");y(f,"REJECT_ALL")})});k.declarative("banner-customize","click",function(){var d=k.$("#cos-banner"),f=d.find('[name\x3d"disclosureDecision"]');z.customize({metricDimensions:[f.val()]}).then(function(){y(d,"ACCEPT_PARTIAL")})});var y=function(d,f){var g=d.find('[name\x3d"consentTypes"]').val();g&&""!==g.trim()&&0!==g.length&&(g=g.split(","),
k.each(g,function(g){if(T.hasOwnProperty(g)&&t.csa&&"function"===typeof t.csa){var n=csa("Events",{producerId:"cdo-privacy"}),p=T[g],r="NO_VALUE"===f,q=p.hasOwnProperty(f)?p[f]:C[f];p=k.contains(q,".")?p.name+q:q;n("log",{schemaId:"cdo_privacy.anonymia.consent_business_metrics.6",producerId:"cdo-privacy",aaaClientName:"ShoppingPortal",consentType:g,consentValue:p,consentInferredValue:f,consentAdditionalAttribute:"null",clientType:d.find('[name\x3d"clientType"]').val(),privacyCustomerId:d.find('[name\x3d"privacyCustomerId"]').val(),
sessionId:d.find('[name\x3d"sessionId"]').val(),userType:d.find('[name\x3d"userType"]').val(),businessDomain:"1",userId:d.find('[name\x3d"userId"]').val(),tollhouseMarketplaceId:"null",uiEventSource:d.find('input[type\x3d"hidden"][name\x3d"disclosureDecision"]').val(),uiEventActionType:r?"bannerPopUp":"buttonClick"})}}))}})});