//tealium universal tag - utag.3558 ut4.0.202601260428, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={view:1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
window.sprChatSettings=window.sprChatSettings||{};window.sprChatSettings={appId:"68f9880e898e1558a91a4831_app_2318924",scope:"MULTI_CONVERSATION",landingScreen:"LAST_CONVERSATION",sessionOrigin:"samsung.com"};(function(){var a,r,n,o,i,s=window,e=s.sprChat;(e&&e.loaded)||((a=document),((r=function(){r.q.push(arguments);}).q=[]),(s.sprChat=r),(s.sprChat.loaded=!0),(n=0),(o='spr-live-chat-widget'),(i=function(){var e=a.getElementById(o),e=(e&&e.parentNode.removeChild(e),a.createElement('script')),t=((e.type='text/javascript'),(e.async=!0),(e.src='https://prod-live-chat.sprinklr.com/api/livechat/handshake/widget/'+s.sprChatSettings.appId),(e.id=o),(e.onerror=function(e){var t,a;++n<=3?setTimeout(i,250):((s.sprChat.loaded=!1),(t='WIDGET_LOAD_FAILED'),(a=e),r.q
.map(function(e){if('subscribeToUpdate'===e[0]&&e[1]&&'loadCompleted'===e[1].topic)return e[1].subscriber;})
.map(function(e){e&&e({response:{error:!0,errorPayload:{type:t,message:a}}});}));}),(e.onload=function(e){if(window.EcommFlutterClient){s.sprChat('disable')}}),a.getElementsByTagName('script')[0]);t.parentNode.insertBefore(e,t);}),'loading'!==a.readyState?i():a.addEventListener('DOMContentLoaded',i));})();window.sprChat('subscribeToUpdate',{topic:'eventTriggered',subscriber:function onEventTriggered({response:{data}}){const{eventType,additional={}}=data;if(eventType==="NEW_CONVERSATION_CREATED"||eventType==="CONVERSATION_CLOSED"||eventType==="CONVERSATION_DELETED"){if(eventType==="NEW_CONVERSATION_CREATED"){utag.link({'link_cat':'sprinklr_chat_events','link_id':'chat start','link_meta':'link_name:chat start','link_position':'sprinklr_events','event_name':'sprinklr_chat_start','sprinklr_vuid':additional.userId,'product_id':window.utag_data.product_id||undefined,'product_name':window.utag_data.product_name||undefined,'site_section1':window.utag_data.site_section1||undefined,'site_section2':window.utag_data.site_section2||undefined,'site_section3':window.utag_data.site_section3||undefined});}
if(eventType==="CONVERSATION_CLOSED"||eventType==="CONVERSATION_DELETED"){utag.link({'link_cat':'sprinklr_chat_events','link_id':'chat end','link_meta':'link_name:chat end','link_position':'sprinklr_events','event_name':'sprinklr_chat_end','sprinklr_vuid':additional.userId,'product_id':window.utag_data.product_id||undefined,'product_name':window.utag_data.product_name||undefined,'site_section1':window.utag_data.site_section1||undefined,'site_section2':window.utag_data.site_section2||undefined,'site_section3':window.utag_data.site_section3||undefined});}}}});if(window.location.pathname.includes("order-confirm")&&typeof b.order_ID!="undefined"&&b.order_ID!=""){window.sprChat('updateConversationContext',{context:{"_c_60818575bb01be725a2c7114":[b.order_ID],"_c_68c4338e5543df57a199b0f7":[b.order_total],"_c_68c433e45543df57a19a539b":[b.tealium_timestamp_utc],"_c_68c42d775543df57a18e4875":[b.product_family],"_c_68c434ba5543df57a19bceb5":[b.product_quantity],"_c_608185ccbb01be725a2cb487":['YES']},includeDeleted:true,});}
}};utag.o[loader].loader.LOAD(id);})("3558","samsung.main");}catch(error){utag.DB(error);}
