//tealium universal tag - utag.3464 ut4.0.202601260428, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<41){u.loader=function(o,a,b,c,l,m){utag.DB(o);a=document;if(o.type=="iframe"){m=a.getElementById(o.id);if(m&&m.tagName=="IFRAME"){b=m;}else{b=a.createElement("iframe");}o.attrs=o.attrs||{};utag.ut.merge(o.attrs,{"height":"1","width":"1","style":"display:none"},0);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";}if(o.id){b.id=o.id;}for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState=="complete"||this.readyState=="loaded"){this.onreadystatechange=null;o.cb();}};}}if(o.type!="img"&&!m){l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}}};}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.scriptrequested=false;u.map={};u.extend=[function(a,b){try{if(1){function getCookie(cname){let name=cname+"=";let ca=document.cookie.split(';');for(let i=0;i<ca.length;i++){let c=ca[i];while(c.charAt(0)==' '){c=c.substring(1);}
if(c.indexOf(name)==0){return c.substring(name.length,c.length);}}
return"";}
let guid=getCookie("guid");let device_model=b['product_id']?b['product_id'].toString():undefined;let device_marketing_name=b['product_name']?b['product_name'].toString():undefined;window.insider_object=window.insider_object||{};window.insider_object.user={"uuid":guid||undefined,"custom":{"ecid":b['cp.s_ecid']||undefined,"device_model":device_model||undefined,"device_marketing_name":device_marketing_name||undefined}}}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:3464");utag.DB(b);var c,d,e,f;u.data={"base_url":"https://##utag_partner_name##.api.useinsider.com/ins.js","partner_name":"samsungusa","partner_id":"10006932"};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};utag.DB("send:3464:EXTENSIONS");utag.DB(b);for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
utag.DB("send:3464:MAPPINGS");utag.DB(u.data);if(!u.data.partner_name){utag.DB(u.id+": Tag not fired: 'Partner Name' variable not populated");return;}
if(!u.data.partner_id){utag.DB(u.id+": Tag not fired: 'Partner ID' variable not populated");return;}
u.data.base_url=u.data.base_url.replace("##utag_partner_name##",u.data.partner_name);u.data.base_url=u.data.base_url+"?id="+u.data.partner_id;if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":null,"loc":"script","id":"utag_3464","attrs":{}});}
utag.DB("send:3464:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("3464","samsung.main"));}catch(error){utag.DB(error);}
