//tealium universal tag - utag.3652 ut4.0.202601260428, Copyright 2026 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={id:id};utag.o[loader].sender[id]=u;u.ev={view:1,link:1};u.initialized=false;u.queue=[];u.clearEmptyKeys=function(object){Object.keys(object).forEach(function(key){if(object[key]===''||object[key]===undefined){delete object[key];}});return object;};u.toBoolean=function(val){val=val||"";return val===true||val.toLowerCase()==="true"||val.toLowerCase()==="on";};u.createDtmConfigObject=function(object){var dtmConfigObject={};var eventProperties=['dtm_email_hash','dtmc_department','dtmc_category','dtmc_sub_category','dtm_items','dtmc_product_id','dtmc_brand','dtmc_upc','dtmc_mpn','dtmc_tcf_string','dtmc_transaction_id','dtm_conv_val','dtm_conv_curr','dtmc_conv_type','dtmc_conv_store_location','custom'];eventProperties.forEach(function(prop){if(prop==='custom'&&object[prop]){Object.keys(object[prop]).forEach(function(key){dtmConfigObject[key]=object[prop][key];});}else if(object[prop]){dtmConfigObject[prop]=object[prop];}});return dtmConfigObject;};u.createQueryString=function(object){var queryString='';Object.keys(object).forEach(function(param){var value=object[param];if(Array.isArray(value)){queryString+='&'+param+'='+encodeURIComponent(JSON.stringify(value));}else{queryString+='&'+param+'='+encodeURIComponent(value);}});return queryString;}
u.createLimitedUrl=function(object){var queryString='';var urlParameter=['dtmc_tcf_string','dtm_email_hash','dtm_conv_curr','dtmc_department','dtmc_category','dtmc_sub_category','dtmc_product_id','dtmc_brand','dtmc_upc','dtmc_mpn','dtmc_transaction_id','dtm_conv_val','dtmc_conv_type','dtmc_conv_store_location'];urlParameter.forEach(function(param){if(object[param]){queryString+='&'+param+'='+object[param];}});return queryString;};u.createDtmItems=function(){if(u.data.product_id.length===0){return'';}
return u.data.product_id.map(function(product,index){var item={product_id:u.data.product_id[index],item_amount:u.data.product_unit_price[index],item_quantity:u.data.product_quantity[index],item_discount:u.data.product_discount[index],};Object.keys(u.data.dtm_items).forEach(function(parameter){item[parameter]=u.data.dtm_items[parameter][index];});return u.clearEmptyKeys(item);});};u.map_func=function(arr,obj,item){var i=arr.shift();obj[i]=obj[i]||{};if(arr.length>0){u.map_func(arr,obj[i],item);}else{obj[i]=item;}};u.map={"dtm_promo_id":"dtm_promo_id","_sm_3652_2":"cachebuster","dtmc_product_id":"dtmc_product_id","dtmc_department":"dtmc_department","dtmc_category":"dtmc_category","dtmc_sub_category":"dtmc_sub_category","_sm_3652_7":"dtmc_brand","cp.AMP_VID":"dtm_user_id","dtm_fid":"dtm_fid","order_total":"dtm_conv_val"};u.extend=[function(a,b){try{b['_sm_3652_2']=Math.floor(10**15+Math.random()*9*10**15);}catch(e){utag.DB(e);}
try{b['_sm_3652_7']="samsung";}catch(e){utag.DB(e);}}];u.send=function(utag_event,data_layer){if(u.ev[utag_event]||u.ev.all!==undefined){utag.DB('send:3652');utag.DB(data_layer);var a,b,c,f,query_params;a=utag_event;b=data_layer;u.data={tag_domain:'',tag_path:'',dtm_cid:'21965',dtm_cmagic:'c6945f',dtm_fid:'',integration_type:'Default',spa_support:'Off',base_url:'https://login.dotomi.com/profile/visit/js/1_0?',dtm_promo_id:'',dtmc_tcf_string:'',dtm_email_hash:'',dtm_user_id:'',dtm_cookie_id:'',cachebuster:'',dtmc_department:'',dtmc_category:'',dtmc_sub_category:'',dtmc_product_id:'',dtmc_brand:'',dtmc_upc:'',dtmc_mpn:'',dtmc_conv_type:'',dtmc_conv_store_location:'',dtmc_transaction_id:'',dtm_conv_val:'',dtm_conv_curr:'',product_id:[],product_quantity:[],product_unit_price:[],product_discount:[],dtm_items:'',dtm_item:[],custom:{}};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};utag.DB('send:3652:EXTENSIONS');utag.DB(data_layer);query_params=[];Object.keys(utag.loader.GV(u.map)).forEach(function(mapping_key){if(data_layer[mapping_key]!==undefined&&data_layer[mapping_key]!==''){var destinations=u.map[mapping_key].split(',');destinations.forEach(function(parameter){if(u.data.hasOwnProperty(parameter)||parameter.indexOf('.')>-1){u.map_func(parameter.split('.'),u.data,data_layer[mapping_key]);}});}});utag.DB('send:3652:MAPPINGS');utag.DB(u.data);var eCommerceMapping=[{eCommerceData:data_layer._corder,name:'dtmc_transaction_id',isArray:false},{eCommerceData:data_layer._csubtotal,name:'dtm_conv_val',isArray:false},{eCommerceData:data_layer._ccurrency,name:'dtm_conv_curr',isArray:false},{eCommerceData:data_layer._cprod,name:'product_id',isArray:true},{eCommerceData:data_layer._cquan,name:'product_quantity',isArray:true},{eCommerceData:data_layer._cprice,name:'product_unit_price',isArray:true},{eCommerceData:data_layer._cpdisc,name:'product_discount',isArray:true}];eCommerceMapping.forEach(function(dataObject){if(!dataObject.isArray){u.data[dataObject.name]=u.data[dataObject.name]||dataObject.eCommerceData||'';}else if(u.data[dataObject.name].length===0&&dataObject.eCommerceData!==undefined&&dataObject.isArray){u.data[dataObject.name]=dataObject.eCommerceData.slice(0);}});u.data.base_url+='dtm_cid='+u.data.dtm_cid;u.data.base_url+="&dtm_cmagic="+u.data.dtm_cmagic;u.data.base_url+="&dtm_fid="+u.data.dtm_fid;if(u.data.order_id||u.data.dtmc_transaction_id){var dtmItem=u.createDtmItems();}
if(u.data.dtm_promo_id){u.data.base_url+="&dtm_promo_id="+u.data.dtm_promo_id;}
if(u.data.dtm_user_id){u.data.base_url+="&dtm_user_id"+"="+u.data.dtm_user_id;}
if(u.data.dtm_cookie_id){u.data.base_url+="&dtm_cookie_id"+"="+u.data.dtm_cookie_id;}
if(u.data.cachebuster){u.data.base_url+='&cachebuster'+'='+u.data.cachebuster;}else{u.data.base_url+='&cachebuster'+'='+data_layer.tealium_random;}
if(document.location.href){u.data.base_url+='&dtmc_loc'+'='+encodeURIComponent(document.location.href);}
if(u.toBoolean(u.data.spa_support)){u.data.base_url+="&dtm_clear_tag=all"}
if(u.data.integration_type==='Default'){if(u.data.order_id||u.data.dtmc_transaction_id){u.data.dtmc_product_id='';u.data.dtm_items=dtmItem||'';}
u.data.base_url+=u.createQueryString(u.createDtmConfigObject(u.clearEmptyKeys(u.data)))}
if(u.data.integration_type==='Limited'){u.data.base_url=u.data.base_url.replace('/js/','/px/');u.data.base_url+=u.createLimitedUrl(u.clearEmptyKeys(u.data));if(u.data.order_id||u.data.dtmc_transaction_id){if(dtmItem){u.data.base_url+="&dtm_items="+encodeURIComponent(JSON.stringify(dtmItem));}}
Object.keys(u.data.custom).forEach(function(key){u.data.base_url+="&"+key+"="+u.data.custom[key];});utag.ut.loader({type:'img',src:u.data.base_url+query_params.join(u.data.qsp_delim)});}else{utag.ut.loader({type:'script',src:u.data.base_url,cb:null,loc:'body',id:'utag_3652',attrs:{}});}
utag.DB('send:3652:COMPLETE');}};utag.o[loader].loader.LOAD(id);}('3652','samsung.main'));}catch(error){utag.DB(error);}
