'use strict';mix_d("CETechCompatibilityZoneCards__compatibility-zone-works-with:compatibility-zone-works-with__kJkBqR1L","exports tslib @p/A @c/aui-bottom-sheet @c/browser-operations @c/csa @c/scoped-dom @c/pagemarker @c/aui-truncate @c/tracking @c/remote-operations @c/logger @c/metrics".split(" "),function(G,f,S,T,U,V,W,X,Y,Z,aa,ba,ca){function g(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var w=g(S),da=g(T),ea=g(U),h=g(W),fa=g(X),ha=g(Y),H=g(ba),p;(function(a){a.DP_CD_DESKTOP_FIND_YOUR_MODEL=
"arcx_cd_dp_dsk_fm";a.DP_CD_MOBILE_FIND_YOUR_MODEL="arcx_cd_dp_mob_fm";a.DP_CD_DESKTOP_SPEC_SEE_MORE="arcx_cd_dp_dsk_ssm";a.DP_CD_MOBILE_SPEC_SEE_MORE="arcx_cd_dp_mob_ssm"})(p||(p={}));var q;(function(a){a.DETAIL_MOBILE="DetailAW";a.DETAIL_DESKTOP="Detail"})(q||(q={}));var ia=function(a){var c={};c.asin=a.asin;c.deviceType=a.deviceType;c.deviceOS=a.deviceOS;c.widgetType=a.widgetType.valueOf();c.marketplaceId=a.marketplaceId;c.customerId=void 0!==a.customerId?a.customerId:null;c.requestId=a.requestId;
c.sessionId=a.sessionId;c.compatibleDevices=a.compatibleDevices?a.compatibleDevices:null;c.compatibleSpecs=a.compatibleSpecs?a.compatibleSpecs:null;try{ca.event(c,"arcx-detail-page","arcx.detail.page.compatibility_detail.2",void 0)}catch(r){H["default"].log("Failed to log nexus metric with error: "+r,"ERROR","arcx-mavericks")}};G._operationNames=["noOp"];G.card=function(){return f.__awaiter(void 0,void 0,void 0,function(){var a,c,r,k,I,x,e,t,J,K,L,M,y,N,O;return f.__generator(this,function(z){switch(z.label){case 0:return a=
ea["default"].setup().define,c=!1,ha["default"].refreshAutoTruncate(),r=aa.setup(),[4,r.noOp()];case 1:return z.sent(),w["default"].on("a:truncate:compatibleDevicesSpecTruncateElement:updated",function(){h["default"].cardRoot.querySelector("#spec_see_more_link")&&!c&&(e("SpecSeeMoreIngressRendered"),c=!0)}),k=h["default"].cardRoot.querySelector("#metric_data"),I={asin:k.getAttribute("data-asin"),deviceType:k.getAttribute("data-device-type"),obfuscatedMarketplaceId:k.getAttribute("data-marketplace"),
placement:"DPWorksWithBelowPOPlacement",productType:k.getAttribute("data-product-type")},x=function(b,d){b=f.__assign(f.__assign(f.__assign({},d),I),{schemaId:b});V.callEventInstance({producerId:"cetech-compatibility"},"log",b,{ent:"all"})},e=function(b){x("cetech_compatibility.compatibilityZoneClientSideEvents.2",{eventName:b})},t=function(b,d,l){x("cetech_compatibility.compatibilityZoneNumericMetric.1",{metricName:b,metricValue:d,metricUnit:l})},J=function(b,d){setTimeout(function(){return t(d+
"BottomSheetScrollDepth",(null===b||void 0===b?void 0:b.scrollTop)||0,"pixels")},150)},K=function(b,d){w["default"].$(".a-sheet-content-container").scroll(function(l){setTimeout(function(){0<w["default"].$(l.target).find("."+b).length&&J(l.target,d)},150)})},L={eventPrefix:"SpecSeeMore",selector:".cpt-zone-spec-see-more-bottom-sheet-content",sheetName:"bottom_sheet_template_spec_see_more"},M={eventPrefix:"FindYourModel",selector:".cpt-zone-fym-bottom-sheet-content",sheetName:"bottom_sheet_template_FYM"},
y=function(b,d,l,ja){var m,P,A;return function(ka){return f.__awaiter(void 0,void 0,void 0,function(){var B,u,C,v,Q,R,D;return f.__generator(this,function(n){switch(n.label){case 0:e(b.eventPrefix+"IngressClicked");B=null===(D=ka.currentTarget)||void 0===D?void 0:D.getAttribute("mbs-id");if(!B)return[2];u=b.sheetName+"-empty-div";m||(C=h["default"].createElement("div"),C.classList.add(u,"aok-hidden"),h["default"].cardRoot.appendChild(C),m=da["default"].create(b.sheetName,"."+u,{height:400}),m.on("afterShow",
function(){P=Date.now();e(b.eventPrefix+"BottomSheetRendered");A&&m.changeHeight(Math.max(A.offsetHeight,300))}),m.on("afterHide",function(){t(b.eventPrefix+"BottomSheetDwellTime",Date.now()-P,"ms")}));v=h["default"].cardRoot.querySelector("#"+B);m.render(function(E){var F;E.innerHTML=(null===v||void 0===v?void 0:v.outerHTML)||"";null===(F=E.querySelector(b.selector))||void 0===F?void 0:F.classList.remove("aok-hidden");A=E});m.show();K(u,b.eventSuffix);Q=Z.createTracking(d,{ref_:l.valueOf(),"page-type":ja.valueOf()});
n.label=1;case 1:return n.trys.push([1,3,,4]),[4,Q()];case 2:return n.sent(),[3,4];case 3:return R=n.sent(),H["default"].log(d+" : Failed to publish "+l+" metric to Clickstream: "+R.toString(),"ERROR"),[3,4];case 4:return[2]}})})}},a("cpt-zone-spec-see-more-bottom-sheet-click","click",y(L,"SpecSeeMoreBottomSheetClickTracking",p.DP_CD_MOBILE_SPEC_SEE_MORE,q.DETAIL_MOBILE)),a("cpt-zone-fym-bottom-sheet-click","click",y(M,"FindYourModelBottomSheetClickTracking",p.DP_CD_MOBILE_FIND_YOUR_MODEL,q.DETAIL_MOBILE)),
t("NumberOfCompatibleDevices",Number(k.getAttribute("data-device-count")),"devices"),[4,fa["default"].visible];case 2:return z.sent(),e("CompatibilityZoneRendered"),h["default"].cardRoot.querySelector("#cpt_zone_FYM_section")&&e("FindYourModelIngressRendered"),k.getAttribute("data-spec-availability")?e("SpecAvailable"):e("SpecUnavailable"),N=h["default"].cardRoot.getElementsByClassName("_Y29tc_mainDiv_3b5FJ")[0],(O=N.dataset.nexusRequestContext)&&ia(JSON.parse(O)),[2]}})})}});
